### ISSUE TITLE
`sys/prctl.h` does not exist in osx 

### ISSUE THREAD

**Issue by chenrui333** [resurrecting-open-source-projects/stress#3]
👋 `sys/prctl.h` does not exist in osx, which is causing the 1.0.6 build failure. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/120878

**Comment by eribertomota** [comment]
@vbendel could you help us? Maybe excluding sys/prctl.h for OSX...

**Comment by vbendel** [comment]
Uff, didn't see that coming. :D

Sure, I can help with that. Though I'm not familiar with Homebrew or any OSX dev, so might be a bit rocky on my end.

Anyway, looking online I don't see any particular alternative how to achieve the same on OSX as what that prctl() does here. So I guess just omitting the functionality for OSX might be a way to go. 

Does the Homebrew building use the `configure` script before building? I 'm thinking of detecting the arch in `configure` script and setting appropriate (new) flag in `config.h`. EDIT: Or rather fight a way with autotools to figure it out :P
Would that be plausible?


Alternative is to figure out a different way to achieve what [the commit](https://github.com/resurrecting-open-source-projects/stress/pull/1/commits/234f01ae9eac4537f5a3a6298021faa866ea571d) does, such that it would work on OSX - perhaps keeping track of the children and sending explicit SIGTERM on parent exit to all? 
I was actually thinking about such before "discovering" prctl(). 

Please let me know your thoughts.

**Comment by p-linnane** [comment]
Hi. Yes, our build uses the `configure` script. Here is our whole build process (we use Ruby):

```
    system "./autogen.sh"
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}"
    system "make", "install"
```

**Comment by vbendel** [comment]
Some research online shows that this is not just an OSX problem, but also on other archs like FreeBSD and very well anything non-Linux. :D

Anyway, after pondering few hours over autoconf docs, I think I found a quite simple solution - see [commit](https://github.com/vbendel/stress/commit/7ae7ebe50f389054f5a78873867b5eef92b8cf97).

Can someone with OSX / FreeBSD / non-linux build environment try it? @chenrui333 , @eribertomota ? 
Feel free to grab a checkout from my [fork](https://github.com/vbendel/stress). I'll sumbit a pull request only once confirmed it fixes the problem on OSX / other.

(otherwise I will try to set up some VM.. sometime next week hopefully)

===============================================================
~~~
### Autogen.sh

[root@localhost stress]# ./autogen.sh
 
Done. You can use the 'clean' option to vanish the source code.
Example of use: $ ./autogen clean


### Configure

[root@localhost stress]# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking sys/prctl.h usability... yes     <<<---
checking sys/prctl.h presence... yes     <<<---  
checking for sys/prctl.h... yes     <<<---
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for alarm... yes
checking for sqrt... no
checking for strerror... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating config.h
config.status: executing depfiles commands


### Build

[root@localhost stress]# make
make  all-recursive
make[1]: Entering directory '/root/devel-stress/stress'
Making all in src
make[2]: Entering directory '/root/devel-stress/stress/src'
gcc -DHAVE_CONFIG_H -I. -I..    -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -g -O2 -MT stress.o -MD -MP -MF .deps/stress.Tpo -c -o stress.o stress.c
mv -f .deps/stress.Tpo .deps/stress.Po
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -g -O2   -o stress stress.o -lm 
make[2]: Leaving directory '/root/devel-stress/stress/src'
Making all in test
make[2]: Entering directory '/root/devel-stress/stress/test'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/devel-stress/stress/test'
make[2]: Entering directory '/root/devel-stress/stress'
make[2]: Leaving directory '/root/devel-stress/stress'
make[1]: Leaving directory '/root/devel-stress/stress'


### Test

[root@localhost stress]# ./src/stress -c 1 -i 1 -m 1 -d 1 &
[1] 33773
[root@localhost stress]# stress: info: [33773] dispatching hogs: 1 cpu, 1 io, 1 vm, 1 hdd

[root@localhost stress]# ps
    PID TTY          TIME CMD
  15927 pts/0    00:00:00 bash
  33773 pts/0    00:00:00 stress
  33774 pts/0    00:00:02 stress
  33775 pts/0    00:00:00 stress
  33776 pts/0    00:00:02 stress
  33777 pts/0    00:00:00 stress
  33778 pts/0    00:00:00 ps
[root@localhost stress]# kill 33773
[root@localhost stress]# ps
    PID TTY          TIME CMD
  15927 pts/0    00:00:00 bash
  33780 pts/0    00:00:00 ps
[1]+  Terminated              ./src/stress -c 1 -i 1 -m 1 -d 1
[root@localhost stress]# 
~~~

**Comment by chenrui333** [comment]
The patch works for me, thanks!!

**Comment by eribertomota** [comment]
> Can someone with OSX / FreeBSD / non-linux build environment try it? @chenrui333 , @eribertomota ?
> Feel free to grab a checkout from my [fork](https://github.com/vbendel/stress). I'll sumbit a pull request only once confirmed it fixes the problem on OSX / other.

@vbendel Sorry. I have Debian only. If needed, we could try to make a GitHub CI test. However, @chenrui333 already said ok for you code.
